WITH -- 7. Calculate the average number of comments and inlinks per post for each blogger
	TOTAL_INLINKS_POST AS (
		SELECT
			P.POST_ID,
			COUNT(I.INL_ID) AS TOTAL_INLINKS_POST
		FROM
			POSTS AS P
			LEFT JOIN INLINKS AS I ON I.POST_ID = P.POST_ID
		GROUP BY
			P.POST_ID
	),
	TOTAL_COMMENTS_POST AS (
		SELECT
			P.POST_ID,
			COUNT(C.COM_ID) AS TOTAL_COMMENTS_POST
		FROM
			POSTS AS P
			LEFT JOIN "comments" AS C ON C.POST_ID = P.POST_ID
		GROUP BY
			P.POST_ID
	)
SELECT
	A."name" AS BLOGGER_NAME,
	COUNT(P.POST_ID) AS TOTAL_POSTS,
	SUM(TI.TOTAL_INLINKS_POST) AS TOTAL_INLINKS,
	SUM(TC.TOTAL_COMMENTS_POST) AS TOTAL_COMMENTS,
	SUM(TI.TOTAL_INLINKS_POST) / COUNT(P.POST_ID) AS AVG_INLINKS_PER_POST,
	SUM(TC.TOTAL_COMMENTS_POST) / COUNT(P.POST_ID) AS AVG_COMMENTS_PER_POST
FROM
	AUTHORS AS A
	LEFT JOIN POSTS AS P ON P.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN TOTAL_INLINKS_POST AS TI ON TI.POST_ID = P.POST_ID
	LEFT JOIN TOTAL_COMMENTS_POST AS TC ON TC.POST_ID = P.POST_ID
GROUP BY
	A."name"
ORDER BY
	AVG_INLINKS_PER_POST DESC,
	AVG_COMMENTS_PER_POST DESC;

WITH -- 8. Identify the most influential bloggers by aggregating MEIBI and MEIBIX scores across their posts

	TOTAL_COMMENTS AS (
		SELECT
			P.BLOGGERS_ID,
			COUNT(C.COM_ID) AS TOTAL_COMMENTS
		FROM
			POSTS AS P
			LEFT JOIN "comments" AS C ON C.POST_ID = P.POST_ID
		GROUP BY
			P.BLOGGERS_ID
	),
	TOTAL_INLINKS AS (
		SELECT
			P.BLOGGERS_ID,
			COUNT(I.INL_ID) AS TOTAL_INLINKS
		FROM
			POSTS AS P
			LEFT JOIN INLINKS AS I ON I.POST_ID = P.POST_ID
		GROUP BY
			P.BLOGGERS_ID
	),
	TOTALS_POST AS (
		SELECT
			P.BLOGGERS_ID,
			SUM(P.MEIBI_SCORE) AS TOTAL_MEIBI,
			SUM(P.MEIBIX_SCORE) AS TOTAL_MEIBIX
		FROM
			POSTS AS P
		GROUP BY
			P.BLOGGERS_ID
	)
SELECT
	A."name",
	TOTAL_MEIBI,
	TOTAL_MEIBIX,
	TOTAL_COMMENTS,
	TOTAL_INLINKS,
	TOTAL_MEIBI + TOTAL_MEIBIX + TOTAL_COMMENTS + TOTAL_INLINKS AS TOTAL_INFLUENCE
FROM
	AUTHORS A
	LEFT JOIN TOTAL_INLINKS AS TI ON TI.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN TOTAL_COMMENTS AS TC ON TC.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN TOTALS_POST AS TP ON TP.BLOGGERS_ID = A.AUTH_ID
ORDER BY
	TOTAL_INFLUENCE DESC;

WITH -- 9. Find the first 100 posts with the highest engagement score (sum of comments and inlinks)
	TOTAL_COMMENTS AS (
		SELECT
			P.BLOGGERS_ID,
			COUNT(C.COM_ID) AS TOTAL_COMMENTS
		FROM
			POSTS AS P
			LEFT JOIN "comments" AS C ON C.POST_ID = P.POST_ID
		GROUP BY
			P.BLOGGERS_ID
	),
	TOTAL_INLINKS AS (
		SELECT
			P.BLOGGERS_ID,
			COUNT(I.INL_ID) AS TOTAL_INLINKS
		FROM
			POSTS AS P
			LEFT JOIN INLINKS AS I ON I.POST_ID = P.POST_ID
		GROUP BY
			P.BLOGGERS_ID
	)
SELECT
	A."name",
	TOTAL_COMMENTS,
	TOTAL_INLINKS,
	TOTAL_COMMENTS + TOTAL_INLINKS AS ENGAGEMENT_SCORE
FROM
	AUTHORS A
	LEFT JOIN TOTAL_INLINKS AS TI ON TI.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN TOTAL_COMMENTS AS TC ON TC.BLOGGERS_ID = A.AUTH_ID
ORDER BY
	ENGAGEMENT_SCORE DESC
LIMIT 100;