-- SELECT -- 4. (With join and distinct) For each blogger, find the total number of comments and inlinks on their posts
-- 	P.BLOGGERS_NAME,
-- 	COUNT(DISTINCT C.COM_ID) AS TOTAL_COMMENTS,
-- 	COUNT(DISTINCT I.INL_ID) AS TOTAL_INLINKS
-- FROM
-- 	POSTS AS P
-- 	LEFT JOIN "comments" AS C ON C.POST_ID = P.POST_ID
-- 	LEFT JOIN INLINKS AS I ON I.POST_ID = P.POST_ID
-- GROUP BY
-- 	P.BLOGGERS_NAME
-- ORDER BY
-- 	TOTAL_INLINKS DESC,
-- 	TOTAL_COMMENTS DESC;
	
WITH -- 4. (With CTE)  For each blogger, find the total number of comments and inlinks on their posts
	TOTAL_COMMENTS AS (
		SELECT
			P.BLOGGERS_ID,
			COUNT(C.COM_ID) AS TOTAL_COMMENTS
		FROM
			POSTS AS P
			LEFT JOIN "comments" AS C ON C.POST_ID = P.POST_ID
		GROUP BY
			P.BLOGGERS_ID
	),
	TOTAL_INLINKS AS (
		SELECT
			P.BLOGGERS_ID,
			COUNT(I.INL_ID) AS TOTAL_INLINKS
		FROM
			POSTS AS P
			LEFT JOIN INLINKS AS I ON I.POST_ID = P.POST_ID
		GROUP BY
			P.BLOGGERS_ID
	)
SELECT
	A."name",
	TOTAL_COMMENTS,
	TOTAL_INLINKS
FROM
	AUTHORS A
	LEFT JOIN TOTAL_INLINKS AS TI ON TI.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN TOTAL_COMMENTS AS TC ON TC.BLOGGERS_ID = A.AUTH_ID
ORDER BY
	TOTAL_INLINKS DESC,
	TOTAL_COMMENTS DESC;
	
SELECT -- 4. (With not normalised values) For each blogger, find the total number of comments and inlinks on their posts
	A."name" AS AUTHOR_NAME,
	-- P.POST_ID,
	SUM(P.NR_RETRIVED_COMMENTS) AS TOTAL_COMMENTS,
	SUM(P.NR_RETRIVED_INLINKS) AS TOTAL_INLINKS
FROM
	AUTHORS AS A
	LEFT JOIN POSTS AS P ON P.BLOGGERS_ID = A.AUTH_ID
	-- WHERE A."name" = 'Robin Wauters'
GROUP BY
	-- P.POST_ID
	A."name"
ORDER BY
	TOTAL_INLINKS DESC,
	TOTAL_COMMENTS DESC;

WITH -- 5. Identify the most influential bloggers based on the average number of inlinks per post
	TOTAL_INLINKS_POST AS (
		SELECT
			P.POST_ID,
			COUNT(I.INL_ID) AS TOTAL_INLINKS_POST
		FROM
			POSTS AS P
			LEFT JOIN INLINKS AS I ON I.POST_ID = P.POST_ID
		GROUP BY
			P.POST_ID
	)
SELECT
	A."name" AS BLOGGER_NAME,
	COUNT(P.POST_ID) AS TOTAL_POSTS,
	SUM(TI.TOTAL_INLINKS_POST) AS TOTAL_INLINKS,
	SUM(TI.TOTAL_INLINKS_POST) / COUNT(P.POST_ID) AS AVG_INLINKS_PER_POST
FROM
	AUTHORS AS A
	LEFT JOIN POSTS AS P ON P.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN TOTAL_INLINKS_POST AS TI ON TI.POST_ID = P.POST_ID
GROUP BY
	A."name"
ORDER BY
	TOTAL_INLINKS DESC,
	AVG_INLINKS_PER_POST DESC;

SELECT -- 6. Find the first 100 most commented posts along with their authors
    A."name" AS author_name,
    P.title AS post_title,
    COUNT(C.COM_ID) AS comment_count
FROM 
 	POSTS AS P          
	INNER JOIN AUTHORS AS A ON P.BLOGGERS_ID = A.AUTH_ID
	LEFT JOIN "comments" AS C ON C.POST_ID = P.POST_ID
GROUP BY 
	P.title, A."name"
ORDER BY 
	comment_count DESC
LIMIT 100;
