CREATE EXTENSION PG_STAT_STATEMENTS;

SELECT
	PG_STAT_STATEMENTS_RESET ();

SELECT
	*
FROM
	PG_STAT_STATEMENTS_INFO;

SELECT
	CASE
		WHEN QUERY ~ '^SELECT -- \d+' THEN CAST(
			SUBSTRING(
				QUERY
				FROM
					'SELECT -- (\d+)'
			) AS INTEGER
		)
		WHEN QUERY ~ '^WITH -- \d+' THEN CAST(
			SUBSTRING(
				QUERY
				FROM
					'WITH -- (\d+)'
			) AS INTEGER
		)
		ELSE 0
	END AS QUERY_NUMBER,
	USERID::REGROLE AS USERID,
	DATNAME AS DBNAME,
	-- SUBSTRING(QUERY, 1, 100) AS SHORT_QUERY,
	QUERY,
	CALLS,
	ROWS,
	ROWS / CALLS AS MEAN_ROWS,
	ROUND(TOTAL_EXEC_TIME::NUMERIC, 2) AS TOTAL_EXEC_TIME_MS,
	ROUND(MIN_EXEC_TIME::NUMERIC, 2) AS MIN_EXEC_TIME_MS,
	ROUND(MAX_EXEC_TIME::NUMERIC, 2) AS MAX_EXEC_TIME_MS,
	ROUND(MEAN_EXEC_TIME::NUMERIC, 2) AS MEAN_EXEC_TIME_MS,
	ROUND(STDDEV_EXEC_TIME::NUMERIC, 2) AS STDDEV_EXEC_TIME_MS
FROM
	PG_STAT_STATEMENTS
	INNER JOIN PG_DATABASE ON DBID = OID
WHERE
	QUERY LIKE 'SELECT -- %'
	OR QUERY LIKE 'WITH -- %'
ORDER BY
	QUERY_NUMBER;