-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.authors
(
    auth_id integer NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    meibi integer,
    meibix integer,
    avg_words numeric,
    avg_words_len_nostop numeric,
    CONSTRAINT authors_pkey PRIMARY KEY (auth_id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    com_id integer NOT NULL,
    post_id integer,
    content text COLLATE pg_catalog."default",
    author character varying COLLATE pg_catalog."default",
    date date,
    vote integer,
    CONSTRAINT comments_pkey PRIMARY KEY (com_id)
);

CREATE TABLE IF NOT EXISTS public.inlinks
(
    inl_id integer NOT NULL,
    post_id integer,
    title text COLLATE pg_catalog."default",
    author character varying COLLATE pg_catalog."default",
    date date,
    url text COLLATE pg_catalog."default",
    CONSTRAINT inlinks_pkey PRIMARY KEY (inl_id)
);

CREATE TABLE IF NOT EXISTS public.posts
(
    post_id integer NOT NULL,
    title text COLLATE pg_catalog."default",
    bloggers_name character varying COLLATE pg_catalog."default",
    bloggers_id integer,
    nr_of_comments integer,
    content text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    date date,
    nr_retrived_inlinks integer,
    nr_retrived_comments integer,
    post_len integer,
    post_len_nostop integer,
    avg_post_len numeric,
    avg_post_len_nostop numeric,
    meibi_score numeric,
    meibix_score numeric,
    CONSTRAINT posts_pkey PRIMARY KEY (post_id)
);

ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inlinks
    ADD CONSTRAINT inlinks_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.posts (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT posts_bloggers_id_fkey FOREIGN KEY (bloggers_id)
    REFERENCES public.authors (auth_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;